### ISSUE TITLE
VFS read-only doesn't work.

### ISSUE THREAD

**Issue by N70** [N70/deltaOS#29]
Tested in latest dev commit. Files in /system mount can be edited.

**Comment by N70** [comment]
Yes, the readOnly variable is true, @MultHub

**Comment by MultHub** [comment]
@N70 #30

**Comment by MultHub** [comment]
![it just werks™](https://cloud.githubusercontent.com/assets/7152794/19090008/e767579c-8a7c-11e6-9b8e-b556fb80628b.png)

**Comment by N70** [comment]
Thanks. It works!
